SET AUTOCOMMIT = 0;

SELECT @@AUTOCOMMIT;

START TRANSACTION;
	DELETE FROM facturas 
    where id_factura=14 and id_factura=15;
rollback;
COMMIT;


START TRANSACTION;
	INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Franco','Armani','Colombia 32',1636,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Paulo','Díaz','Chile 132',1540,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Milton','Casco','Triunvirato 324',1540,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'David','Martinez','Santiago del Estero 514',1640,'Buenos Aires');
    SAVEPOINT numuno;
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Pablo','Solari','Bouchard 6123',1870,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Agustin','Palavecino','Drysdale 3312',1620,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Santiago','Simon','Talcahuano 3134',1880,'Buenos Aires');
    INSERT INTO clientes(ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,PROVINCIA_CLIENTE) 
    VALUES (NULL,'Bruno','Zuculini','Armenia 2132',1740,'Buenos Aires');
    SAVEPOINT numdos;
    Release SAVEPOINT numuno;
   COMMIT;